#!/bin/bash
# Borra los archivos temporales

declare -r TEMPDIR="/var/www/simape/tmp"
declare -i TODAY=$( date +%s --date="`date +'%Y-%m-%d'`" )


cd ${TEMPDIR}
for TEMPFILE in $( ls ); do
    FILEMODTIME=`stat -c "%Y" ${TEMPFILE}`
    if [ ${FILEMODTIME} -lt ${TODAY} ]
    then
        #echo "Borrando ${TEMPFILE}..."
        rm -f ${TEMPFILE}
    fi
done
